version: "3.9"
services:
  fastapi:
    build: .
    ports:
      - "${FASTAPI_PORT}:${FASTAPI_PORT}"
    networks:
      - default-network
    environment:
      DATABASE_SCHEME: ${DATABASE_SCHEME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      FASTAPI_PORT: ${FASTAPI_PORT}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:13.16
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - default-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  default-network:
    name: fastapi-network
    driver: bridge
volumes:
  pg_data: